### ISSUE TITLE
How to remove negative circles in 2.0

### ISSUE THREAD

**Issue by crystalfp** [Fennec-hub/three-viewport-gizmo#16]
Just updated  three-viewport-gizmo to 2.0.0. Besides the not updated [documentation](https://fennec-hub.github.io/three-viewport-gizmo/api.html), how could I remove the negative axis circles?
Before, this worked perfectly:
```
nx: {colors: {main: "#FF0000"}, circle: false, line: false},
```
But in 2.0.0 this does not work and gives typescript errors.
Also putting `opacity: 0` has no effect. The circles remains visible.
Thanks for looking!

**Comment by crystalfp** [comment]
Seems I need to put:
```
nx: {scale: 0}
```
to remove the negative axis circle.
Not elegant, but for now it is a good workaround.
Thanks for this useful gizmo!

**Comment by Fennec-hub** [comment]
> Not updated documentation

The documentation and updated examples are on the the way, I'm still refining the new options and testing the cube configuration... At the moment you can check the new configuration options here [types.ts](https://github.com/Fennec-hub/three-viewport-gizmo/blob/bae78e2b73aabcd931d244fc2605568d5b321da7/lib/types.ts#L15), the jsDoc is up to date.

> opacity: 0 has no effect.

Yep, Opacity isn't working! Turns out this [Utility function](https://github.com/Fennec-hub/three-viewport-gizmo/blob/main/lib/utils/updateAxis.ts) is overriding the opacity, I'll fix it with next patch.

> Not elegant, but for now it is a good workaround.

`{ scale: 0 }` and (the fixed) `{ opacity: 0 }` does the trick, but yes, it's still a workaround, there is a clear need for an `{ enabled }` options.

Thanks for testing the v2, I'll notify you with new updates!

**Comment by Fennec-hub** [comment]
> Not updated documentation

The documentation and examples are up to date! Please check the new [API documentation](https://fennec-hub.github.io/three-viewport-gizmo/api.html), for the new configuration options.

> opacity: 0 has no effect.

Fixed the utility function, opacity dosn't get overridden, please try it, and let me know if anything goes wrong.

> Not elegant, but for now it is a good workaround.

I've added a new `{ enabled: boolean }` options for each axis, with the new version, all you have to do is `{ enabled: false }`, to disable any axis!

Thanks again for the much appreciated review!
