### ISSUE TITLE
The legacy project doesn't fully support the nullish coalescing operator ??

### ISSUE THREAD

**Issue by EkkoCrystal** [Fennec-hub/three-viewport-gizmo#20]
The code contains the nullish coalescing operator ??, and the legacy project doesn't fully support it. It would require modifying multiple configurations. Is it possible to remove ?? to ensure compatibility with the old project?
For compatibility issues with the Vue version, please provide the dependency version numbers.

**Comment by Fennec-hub** [comment]
This library doesn't have any production `vue` dependency. More over the issue is likely related to the transpiler not converting the ?? operator properly. As a fix, try to set the correct browser target in your build tool. 

If you're using Vite, you can add support for older environments with the [Vite Legacy Plugin](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy). 

For Babel, the [babel-plugin-transform-nullish-coalescing-operator](https://babeljs.io/docs/babel-plugin-transform-nullish-coalescing-operator) can handle this operator.
